# Site settings
title: MentalWhiteNoise
email: github@MentalWhiteNoise.com
description: > # this means to ignore newlines until "baseurl:"
  A different way of thinking
baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://n1nfmind.com" # the base hostname & protocol for your site
github_username:  MentalWhiteNoise
theme: jekyll-theme-slate

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

# Outputting
permalink: date
